### PR TITLE
Deprecate Messenger feature

### LINKED ISSUE #2622: Enabling Messenger chat trigger errors
## ✍️ Describe the bug

Enabling the messenger chat button triggers several errors in the console:

`Access to XMLHttpRequest at 'https://web.facebook.com/plugins/customer_chat/SDK/?app_id=&attribution=fbe_woocommerce&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df2d1f3cb6736c4%26domain%3Ditsanothertestsite.mystagingwebsite.com%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Fitsanothertestsite.mystagingwebsite.com%252Ff20bca75db2a22c%26relation%3Dparent.parent&current_url=https%3A%2F%2Fitsanothertestsite.mystagingwebsite.com%2F&event_name=chat_plugin_sdk_facade_create&is_loaded_by_facade=true&loading_time=0&locale=en_US&log_id=478eec60-bcae-46f2-a069-2bf63aa38c60&page_id=102798312634091&request_time=1692687350867&sdk=joey&should_use_new_domain=false&suppress_http_code=1' from origin 'https://itsanothertestsite.mystagingwebsite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xfbml.customerchat.js:117     GET https://web.facebook.com/plugins/customer_chat/SDK/?app_id=&attribution=fbe_woocommerce&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fx%2Fconnect%2Fxd_arbiter%2F%3Fversion%3D46%23cb%3Df2d1f3cb6736c4%26domain%3Ditsanothertestsite.mystagingwebsite.com%26is_canvas%3Dfalse%26origin%3Dhttps%253A%252F%252Fitsanothertestsite.mystagingwebsite.com%252Ff20bca75db2a22c%26relation%3Dparent.parent&current_url=https%3A%2F%2Fitsanothertestsite.mystagingwebsite.com%2F&event_name=chat_plugin_sdk_facade_create&is_loaded_by_facade=true&loading_time=0&locale=en_US&log_id=478eec60-bcae-46f2-a069-2bf63aa38c60&page_id=102798312634091&request_time=1692687350867&sdk=joey&should_use_new_domain=false&suppress_http_code=1 net::ERR_FAILED 400`

## 🚶‍♀️ Steps to reproduce

1. Go to Marketing > Facebook > Messenger and Enable Messenger	
2. Check the browser console and notice several errors
3. Disable messenger chat and notice all errors disappear

## ✔️ Expected behavior

Enabling messenger chat shouldn't trigger these errors. 

## Affected users

https://wordpress.org/support/topic/errors-307/ (led to [this review](https://wordpress.org/support/topic/bad-plugin-157/))

### PR DESCRIPTION
**Pull request by layoutd**
### Changes proposed in this Pull Request:

This disables and deprecates all Messenger functionality following https://github.com/woocommerce/facebook-for-woocommerce/issues/2622#issuecomment-2004533578.

- Closes #2622 
- Related to #2708 

This PR should:
- Remove the Messenger deprecation notice added in release 3.1.12.
- Remove all Messenger-related settings from the options table
- Remove the Messenger tab from the Facebook for WooCommerce settings.
- Remove the code that injects the Messenger Chat plugin on the store's front end.

It doesn't delete any files or methods – simply marks them as deprecated for posterity. If this seems _too safe_, the unused files could be deleted in a subsequent PR or release.

- [x] Do the changed files pass `phpcs` checks? Please remove `phpcs:ignore` comments in changed files and fix any issues, or delete if not practical.

### Detailed test instructions:

For all tests, confirm no errors in log or browser console.
**Install and upgrade...**
1. Start by installing Facebook for WooCommerce fresh in version 3.1.11: 39ee6d306207c5b3fe4301031fe40f0a65513e03
```
# clone repo
gh repo clone woocommerce/facebook-for-woocommerce
# check out 3.1.11
git checkout 39ee6d306207c5b3fe4301031fe40f0a65513e03
# build extension
nvm use && composer i && npm i && npm run build:dev
```
2. Activate and connect to a Facebook account
3. Confirm "Messenger" tab appears in extension settings and loads (`wp-admin/admin.php?page=wc-facebook&tab=messenger`):

image

5. Enable messenger and confirm the chat appears on shop (probably with a slight delay, and with `has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.` error in the console):
image

7. Check for `.fb-customerchat` DOM element or the `xfbml.customerchat.js` script to see that the chat plugin is being injected:
image
image

8. Upgrade to current version:
``` 
git checkout develop
```
9. Visit extension settings (`wp-admin/admin.php?page=wc-facebook`) and confirm the deprecation notice appears **(Don't dismiss!!)**:
image
(It should also appear on the messenger settings and other places, like Plugins or the Orders page)
image

10. Check for Facebook Messenger options:
```
SELECT * FROM `wp_options` WHERE option_name LIKE 'wc_facebook%' AND option_name LIKE '%messenger%';
# Should have 1 (but maybe up to 4) records
```

11. Finally, upgrade to this PR:
```
git checkout remove/deprecate-facebook-messenger-feature
# build if necessary
```
12. Force migration by updating the version to `3.2.0` in `facebook-for-woocommerce.php`:
```
 * Version: 3.2.0
 …
	const PLUGIN_VERSION = '3.2.0'; // WRCS: DEFINED_VERSION.
 ```

**Confirm Messenger settings page is gone**
1. Navigate to the Facebook extension `/wp-admin/admin.php?page=wc-facebook`
2. Confirm the "Messenger" settings tab no longer appears.
4. Navigate to `/wp-admin/admin.php?page=wc-facebook&tab=messenger`
11. Confirm no settings page is loaded (same behavior as if you put `&tab=nopagehere`)

**Confirm settings DB records erased**
1. Check that no messenger options are left in the DB:
```
SELECT * FROM `wp_options` WHERE option_name LIKE 'wc_facebook%' AND option_name LIKE '%messenger%';
# Should not return any records
```
**Confirm messenger scripts are no longer injected**
1. In shop, confirm no errors in console.
2. Confirm messenger chat no longer appears
3. Confirm `.fb-customerchat` DOM element and the `xfbml.customerchat.js` script are no longer present.

**Confirm messenger deprecation notice removed**
1. The messenger deprecation notice should no longer appear anywhere (Facebook for WooCommerce settings, Plugins, Orders, etc.)

**Bonus**
- Smoketest the extension
- Run unit tests

### Changelog entry

> Update - Remove the sunsetted Messenger Chat feature.

### CODE REVIEW

File: facebook-commerce.php [hunk 1]
```diff
@@ -2746,14 +2743,18 @@ public function is_legacy_feed_file_generation_enabled() {
...
 	 * @return bool
 	 */
 	public function is_messenger_enabled() {
+		return false;
+
 		/**
 		 * Filters whether the Facebook messenger is enabled.
 		 *
 		 * @since 1.10.0
+		 * @deprecated 3.2.0
```
Comment (rawdreeg) [inline facebook-commerce.php:2757]: nit: since the filter is never run and we return false. I think we can remove it.

**Review by rawdreeg — COMMENTED** [review]
I tested the removal. and  that looks good.

Along with the one nit pick I left in the comments. I wonder since we're only marking the class as deprecated without removing it, we shouldn't have a `_doing_it_wrong` call when try to access the class method.

This comment also applies to the deprecated method in the `WC_Facebookcommerce_Integration` class.

**Comment by layoutd** [comment]
Thanks @rawdreeg 

> Along with the one nit pick I left in the comments. I wonder since we're only marking the class as deprecated without removing it, we shouldn't have a `_doing_it_wrong` call when try to access the class method.

Yeah, I've gone back and forth on that. I doubt there are many people extending or invoking the Messenger class or methods directly, but the extension has a huge user base and I'm a bit gun shy about breaking things now 😳 

I'll look into removing the code altogether (I want to see some prior art just to be sure I'm doing it right).

**Comment by rawdreeg** [comment]
> Thanks @rawdreeg
> 
> > Along with the one nit pick I left in the comments. I wonder since we're only marking the class as deprecated without removing it, we shouldn't have a `_doing_it_wrong` call when try to access the class method.
> 
> Yeah, I've gone back and forth on that. I doubt there are many people extending or invoking the Messenger class or methods directly, but the extension has a huge user base and I'm a bit gun shy about breaking things now 😳
> 
> I'll look into removing the code altogether (I want to see some prior art just to be sure I'm doing it right).

I am happy to deprecate gracefully. but if the feature won't work from FB then it will probably break one way or another :-D

**Comment by budzanowski** [comment]
I strongly suggest removing the code, tests, anything related to chat at this point.

**Comment by budzanowski** [comment]
@layoutd I have created #2721 for visibility and tagged you there.

File: facebook-commerce.php [hunk 2]
```diff
@@ -2493,16 +2493,8 @@ public function get_product_description_mode() {
 	 * @return string
 	 */
 	public function get_messenger_locale() {
-		/**
```
Comment (budzanowski) [inline facebook-commerce.php:2506]: I assume that you are not deleting this because it is a public interface.

My gut feeling is that we could still delete this and others as well. The filters are the integration points for merchants. Having the methods exposed was a mistake. 

I don't mind playing it safe so if we want to keep those let's keep them.

Comment (layoutd) [reply facebook-commerce.php:2506]: Thanks, yeah, that's the concern I was going to ask about. I would be surprised if anyone was actually using these methods, but for safety I would leave them for this release, and then remove them in a following release (to give at least a couple weeks to catch the warning).

**Comment by layoutd** [comment]
I've gone through and removed _almost_ everything. I left a few public properties and methods that can be fully removed a handful of releases after 3.2.0:
- #2724

**Review by rawdreeg — APPROVED** [review]
Thanks for working on this.

**Comment by layoutd** [comment]
Thanks for the 👀 @rawdreeg. I'm going to leave it awaiting merge until April 26, so it can be released on the 30th or on May 7.

File: facebook-commerce.php (hunk 2 above)
Comment (layoutd) [reply facebook-commerce.php:2506]: See 
- https://github.com/woocommerce/facebook-for-woocommerce/issues/2724
