### PR TITLE
Fix deprecated notices coming from ported skyverge code.

### LINKED ISSUE #1966: Deprecated notices coming from wc_facebook_background_product_sync AJAX endpoint
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

Hello team,

Recently we fixed an bug in WooCommerce core and we deprecated `WC_Session_Handler::nonce_user_logged_out`, and the SkyVerge's plugin framework used in this extension is calling this deprecated function in an ajax request. I have already started an issue in the framework side: https://github.com/skyverge/wc-plugin-framework/issues/541

There's also some reports in wp.org: https://wordpress.org/support/topic/nonce_user_logged_out-function-is-deprecated/

## 🚶‍♀️ Steps to reproduce

1. Enable `WP_DEBUG` and `WP_DEBUG_DISPLAY`, see more in https://wordpress.org/support/article/debugging-in-wordpress/
2. Just still WooCommerce and Facebook for WooCommerce, also make all initial set up of the plugin.
3. While syncing products to Facebook note that there's some deprecated notices from `WC_Session_Handler::nonce_user_logged_out` coming from SkyVerge's plugin framework.

Note that's required to enable debugging in WP to see those messages, so not a huge bug or issue, probably could be just fine to advice users to disable PHP errors in production, anyway it's nice if we could patch it soon.

## ✔️ Expected behavior
No deprecated messages.

### PR DESCRIPTION
**Pull request by message-dimke**
### Changes proposed in this Pull Request:

Integrating a deprecated notice fix from Sky Verge repository https://github.com/godaddy-wordpress/wc-plugin-framework/pull/547 into our codebase.

Closes #1966 .

### Detailed test instructions:

1. While syncing products to Facebook note that there's some deprecated notices from WC_Session_Handler::nonce_user_logged_out coming from SkyVerge's plugin framework.

### Changelog entry

> Fix - Deprecated notice fix.

### CODE REVIEW

File: includes/Framework/Utilities/BackgroundJobHandler.php [hunk 1]
```diff
@@ -127,20 +127,35 @@ public function maybe_handle() {
...
+		 *  for logged-out users to use the customer session ID instead of 0 for user ID. We *want* to check
+		 *  against a UID of 0 (since that's how the nonce was created), so we temporarily pause the
+		 *  logged-out nonce hijacking before standing aside.
+		 *
+		 * @see \WC_Session_Handler::init() when the action is hooked
+		 * @see \WC_Session_Handler::nonce_user_logged_out() WC < 5.3 callback
+		 * @see \WC_Session_Handler::maybe_update_nonce_user_logged_out() WC >= 5.3 callback
+		 */
+		if ( Compatibility::is_wc_version_gte('5.3') ) {
+			$callback = [ WC()->session, 'maybe_update_nonce_user_logged_out' ];
```
Comment (rawdreeg) [inline includes/Framework/Utilities/BackgroundJobHandler.php:146]: One small thing. Can we keep the array syntax consistent with the phpcs ruleset?

Comment (rawdreeg) [reply includes/Framework/Utilities/BackgroundJobHandler.php:146]: Nice. Thanks @ibndawood

**Review by rawdreeg — APPROVED** [review]
Looks good to see. Thanks @message-dimke

File: includes/Framework/Utilities/BackgroundJobHandler.php [hunk 2]
```diff
@@ -163,14 +163,19 @@ protected function is_queue_empty() {
...
+				WHERE option_name LIKE %s
+				AND ( option_value LIKE %s OR option_value LIKE %s )",
+				$key,
+				$queued,
+				$processing
+			)
+		);
 
-		return ( $count > 0 ) ? false : true;
+		return ! ( $count > 0 );
```
Comment (budzanowski) [inline includes/Framework/Utilities/BackgroundJobHandler.php:178]: why not just use `$count == 0`?

It fits well with the name of the method. Just a nitpick - it can be ignored.

Comment (message-dimke) [reply includes/Framework/Utilities/BackgroundJobHandler.php]: I did `intval( $count ) === 0`, maybe redundant, but we get a string inside the `count` and to pass code styling check we need `===`
