### PR TITLE
Fix #2018 - Correct Content IDs in Purchase event

### LINKED ISSUE #2018: Purchase Event Content IDs mismatch from earlier events for variable products
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
I have a variable product with SKU of `GTBD-MP` and ID 314 and it has 2 variants, with SKUs `GTBD-MP-1` and `GTBD-MP-2`, and IDs 315 and 316 respectively. I am using AJAX to add items to cart. When I add `GTBD-MP-1` to the cart, it correctly sends an `AddToCart` event with a content ID of `GTBD-MP-1_315`. This occurs for other events as well such as `InitiateCheckout`. However, when it gets to the `Purchase` event, it is using a Content ID of `GTBD-MP_314`. As this does not match any of the prior events Facebook is showing me an error in the Events console as per below screenshot. This looks like it is using the parent product instead of the variation.

image

Here is what the `AddToCart` event looks like:
image

Here is what the `Purchase` event looks like (The Content ID does not match the `AddToCart` event):
image

## 🚶‍♀️ Steps to reproduce

1. Ensure Facebook for Woocommerce is installed and working correctly (i.e. events are flowing through)
1. Create a variable product. Give it a SKU of "X" and let's say it has an ID of 1.
1. Add a variation under this product. Give it a SKU of "Y" and let's say it has an ID of 2.
1. Go through a purchase and track the parameters sent with the events on Facebook
1. All events up to purhcase correctly show the Content ID of "Y_2" but the Purchase event has a Content ID of "X_1"

## ✔️ Expected behavior
In all events, Facebook should receive a content ID of "Y_2"

### PR DESCRIPTION
**Pull request by dgurram**
### Changes proposed in this Pull Request:

Fixes mismatch of Content IDs between events. Use `get_product()` on order item which applies the logic - if `variation_id` is set then prefer that over `product_id` in order to get the relevant product. That ends up producing the same Content IDs as earlier events in the purchase. It works the same as before for simple products as `variation_id` is not set on the order item.

Closes #2018.

### How to test the changes in this Pull Request:

As per Steps to Reproduce in #2018.

### Changelog entry

> Fix - Correct Content IDs in Purchase event for variable products

### CODE REVIEW

**Comment by haszari** [comment]
Thanks for logging and fixing this @dgurram ! @rcstr can you review this sometime this week? If it's working well and safe perhaps we can include in next release.

File: facebook-commerce-events-tracker.php [hunk 1]
```diff
@@ -889,8 +889,13 @@ public function inject_purchase_event( $order_id ) {
...
 
-				if ( $product = isset( $item['product_id'] ) ? wc_get_product( $item['product_id'] ) : null ) {
-
+				$product = null;
+				if ( isset( $item['variation_id'] ) ) {
+					$product = wc_get_product( $item['variation_id'] );
+				} else if ( isset( $item['product_id'] ) ) {
+					$product = wc_get_product( $item['product_id'] );
+				}
+				if ( $product ) {
```
Comment (rcstr) [inline facebook-commerce-events-tracker.php:898]: What do you think if we use `$item->get_product()` which will do the same check?

Code reference: https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-order-item-product.php#L326-L331

```suggestion
				$product = $item->get_product();
				
				if ( $product ) {
```

**Review by rcstr — COMMENTED** [review]
thank you for opening this PR @dgurram. I left a suggestion, let me know your thoughts 👍🏽

File: facebook-commerce-events-tracker.php (hunk 1 above)
Comment (dgurram) [reply facebook-commerce-events-tracker.php:898]: Great suggestion - that's far better. I didn't know that existed.

**Review by rcstr — APPROVED** [review]
thank you @dgurram. Changes work great
