### PR TITLE
Deletes the product from facebook once it is switched to draft.

### LINKED ISSUE #2547: Products remain on Facebook when set to draft
## ✍️ Describe the bug

Typically, when you publish a product it's synced to Facebook. When you set the same product to private or hidden, it's removed from Facebook. However, unlike when hidden and set to private, products remain on Facebook when set to draft. 

## 🚶‍♀️ Steps to reproduce

1. Sync products to Facebook as usual
2. Set the product to draft
3. Notice the product remains on Facebook while the Facebook sync widget returns "Product is not published"

## ✔️ Expected behavior

Published products should be removed from Facebook once set to draft

### PR DESCRIPTION
**Pull request by krutidugade**
### Changes proposed in this Pull Request:

Products are visible on Facebook even after switching to draft. This PR deletes the product from Meta Commerce Manager once the product status is switched to draft.

Closes #2547.

_Replace this with a good description of your changes & reasoning._

- [x] Do the changed files pass `phpcs` checks? Please remove `phpcs:ignore` comments in changed files and fix any issues, or delete if not practical.

### Detailed test instructions:

1. Install and activate the Facebook for WooCommerce plugin
2. Go to Meta Commerce Manager
3. Look for a specific product and note the ID
4. Go to WP-Admin > Products and edit the same product
5. Change the product status to draft and update
6. Look for the same product under Meta Commerce Manager
7. Verify the product isn't visible - compare product ID

### Additional details:

The issue was previously fixed in [PR 2569](https://github.com/woocommerce/facebook-for-woocommerce/pull/2569). I noticed an issue so submitted the correct code in this PR.

### Changelog entry

> Fix - Products are deleted from facebook once changed to draft.

### CODE REVIEW

File: facebook-commerce.php [hunk 1]
```diff
@@ -1017,6 +1020,22 @@ private function should_update_visibility_for_product_status_change( $new_status
 		return ( $old_status === 'publish' && $new_status !== 'publish' ) || ( $old_status === 'trash' && $new_status === 'publish' ) || ( $old_status === 'future' && $new_status === 'publish' );
 	}
 
+	/**
+	 * Deletes a product from Facebook when status is changed to draft.
+	 *
```
Comment (budzanowski) [inline facebook-commerce.php:1025]: Missing `@since` documentation element. You can use it with `x.x.x` which will be automatically expanded into proper plugin version by the release script.

```suggestion
	 *
	 * @since x.x.x
```

**Review by budzanowski — APPROVED** [review]
