### PR TITLE
Fix - Sync product set when the term name changes.

### LINKED ISSUE #2344: Product sets title updates aren't automatically synced to Facebook
## 🔎 Isolate the bug

- [x] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [x] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

When a product set name is modified on the site, the change isn't automatically synced to the Facebook catalog. (Changes to set titles are only pushed when new products are added to the set)

## 🚶‍♀️ Steps to reproduce

1. Create a product set in Products > FB Product Sets
2. Allow the set to sync to Facebook
3. Edit the set name (title) in WooCommerce
4. Notice the new name isn't synced to the Facebook catalog

## ✔️ Expected behavior

The new set name should be automatically synced to Facebook just like product title edits are synced to the Facebook catalog.

### PR DESCRIPTION
**Pull request by rawdreeg**
### Changes proposed in this Pull Request:

When a product set name is modified on the site, the change isn't automatically synced to the Facebook catalog. (Changes to set titles are only pushed when new products are added to the set). 

This PR allows product sets' title to be synced on update.

Closes #2344.

_Replace this with a good description of your changes & reasoning._

- [ x] Do the changed files pass `phpcs` checks? Please remove `phpcs:ignore` comments in changed files and fix any issues, or delete if not practical.

### Detailed test instructions:

1. Create a product set in Products > FB Product Sets
2. Allow the set to sync to Facebook
3. Edit the set name (title) in WooCommerce
4. Notice the new name is correctly synced to the Facebook catalog

### Changelog entry

> Fix - Sync product set when the term name changes.

### CODE REVIEW

File: includes/ProductSets/Sync.php [hunk 1]
```diff
@@ -122,7 +140,7 @@ public function add_hooks() {
 		// product set hooks, compare taxonomies the lists before and after saving product to see if must sync
 		add_action( 'created_fb_product_set', array( $this, 'fb_product_set_hook_before' ), 1 );
 		add_action( 'created_fb_product_set', array( $this, 'fb_product_set_hook_after' ), 99 );
-		add_action( 'edited_fb_product_set', array( $this, 'fb_product_set_hook_before' ), 1 );
+		add_action( 'edit_fb_product_set', array( $this, 'fb_product_set_hook_before' ), 1 );
```
Comment (message-dimke) [inline includes/ProductSets/Sync.php:143]: Was this made on purpose, I mean the change to action name? Should we keep it `edited_fb_product_set`?

Comment (rawdreeg) [reply includes/ProductSets/Sync.php:143]: Yes this is on purpose. `edit_fb_product_set` runs before and I allow to get the "before" term name and store it in the static property and compare it to the new name when `edited_fb_product_set` runs later.

**Review by message-dimke — APPROVED** [review]
LGTM! Thanks, @rawdreeg
