### PR TITLE
Fixed AddToCart duplication when other plugins clone cart

### LINKED ISSUE #2544: Meta Add To Cart Reporting Issue
## 🔎 Isolate the bug

- [ X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

This bug appears to be caused when the Add To Cart event is triggered on the website. I can see that on the Meta Events Manager, each time the add to cart event is triggered there are multiple events triggered. This can be seen from the screenshot attached where you will see a massive discrepancy between the server and browser events received. This mismatch of data seems to be majorly with the add to cart but could also be on different events.

## 🚶‍♀️ Steps to reproduce

1. Add product to cart
2. Add to cart event is triggered multiple times
3. Reporting is off due to this

## ✔️ Expected behavior

This action should trigger only one Add to cart event. 

## 🗃 Logs

<details>
	
</details>

`
### WordPress Environment ###

WordPress address (URL): https://www.counterculturestore.co.uk
Site address (URL): https://www.counterculturestore.co.uk
WC Version: 7.5.1
REST API Version: ✔ 7.5.1
WC Blocks Version: ✔ 9.6.6
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 8.0.28
PHP Post Max Size: 16 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.38-MariaDB-0ubuntu0.20.04.1
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.5.1
WC Database Prefix: idNgTS_
Total Database Size: 1461.30MB
Database Data Size: 1115.76MB
Database Index Size: 345.54MB
idNgTS_woocommerce_sessions: Data: 6.02MB + Index: 1.02MB + Engine InnoDB
idNgTS_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
idNgTS_woocommerce_order_items: Data: 1.52MB + Index: 0.39MB + Engine InnoDB
idNgTS_woocommerce_order_itemmeta: Data: 25.52MB + Index: 12.03MB + Engine InnoDB
idNgTS_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
idNgTS_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_woocommerce_payment_tokenmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
idNgTS_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_actionscheduler_actions: Data: 81.63MB + Index: 47.28MB + Engine InnoDB
idNgTS_actionscheduler_claims: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
idNgTS_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_actionscheduler_logs: Data: 68.61MB + Index: 25.06MB + Engine InnoDB
idNgTS_addonlibrary_addons: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_addonlibrary_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_adfoin_integration: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
idNgTS_adfoin_log: Data: 9.52MB + Index: 0.34MB + Engine InnoDB
idNgTS_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_braapf_product_stock_status_parent: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
idNgTS_braapf_product_variation_attributes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_braapf_term_taxonomy_hierarchical: Data: 0.09MB + Index: 0.14MB + Engine InnoDB
idNgTS_braapf_variable_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_cartflows_ca_cart_abandonment: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
idNgTS_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_cli_cookie_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_cli_cookie_scan_categories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_cli_cookie_scan_cookies: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_cli_cookie_scan_url: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_commentmeta: Data: 0.44MB + Index: 0.42MB + Engine InnoDB
idNgTS_comments: Data: 9.52MB + Index: 9.05MB + Engine InnoDB
idNgTS_commercekit_searches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_commercekit_swatches_cache_count: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_commercekit_waitlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_commercekit_wishlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_commercekit_wishlist_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_dokan_follow_store_followers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_dokan_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_dokan_report_abuse_reports: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_dokan_rma_conversations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_dokan_rma_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_dokan_rma_request_product: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_dokan_shipping_tracking: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_dokan_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_dokan_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_e_events: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_e_notes: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
idNgTS_e_notes_users_relations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_e_submissions: Data: 6.52MB + Index: 6.66MB + Engine InnoDB
idNgTS_e_submissions_actions_log: Data: 1.52MB + Index: 1.16MB + Engine InnoDB
idNgTS_e_submissions_values: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
idNgTS_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_gf_entry: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
idNgTS_gf_entry_meta: Data: 0.39MB + Index: 0.50MB + Engine InnoDB
idNgTS_gf_entry_notes: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
idNgTS_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_gf_form_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
idNgTS_gf_form_revisions: Data: 0.47MB + Index: 0.03MB + Engine InnoDB
idNgTS_gf_form_view: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
idNgTS_gf_rest_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_gla_budget_recommendations: Data: 0.20MB + Index: 0.11MB + Engine InnoDB
idNgTS_gla_merchant_issues: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_gla_shipping_rates: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_jetpack_waf_blocklog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_jet_appointments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_appointments_excluded: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_appointments_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_post_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_review_comments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_review_guests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_review_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_review_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_jet_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_nx_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_nx_posts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_nx_stats: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
idNgTS_options: Data: 13.47MB + Index: 2.44MB + Engine InnoDB
idNgTS_postmeta: Data: 121.55MB + Index: 48.14MB + Engine InnoDB
idNgTS_posts: Data: 19.50MB + Index: 3.89MB + Engine InnoDB
idNgTS_premmerce_bundles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_premmerce_bundles_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_rank_math_analytics_ga: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
idNgTS_rank_math_analytics_gsc: Data: 29.39MB + Index: 39.19MB + Engine InnoDB
idNgTS_rank_math_analytics_inspections: Data: 5.48MB + Index: 0.50MB + Engine InnoDB
idNgTS_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_rank_math_analytics_objects: Data: 0.38MB + Index: 0.17MB + Engine InnoDB
idNgTS_rank_math_internal_links: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
idNgTS_rank_math_internal_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
idNgTS_rank_math_redirections: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
idNgTS_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_revslider_sliders: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_slides: Data: 11.52MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_static_slides: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
idNgTS_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_sfa_abandoned_carts: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
idNgTS_snippets: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
idNgTS_social_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_sp_domain_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_termmeta: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
idNgTS_terms: Data: 0.30MB + Index: 0.28MB + Engine InnoDB
idNgTS_term_relationships: Data: 1.27MB + Index: 1.11MB + Engine InnoDB
idNgTS_term_taxonomy: Data: 0.33MB + Index: 0.31MB + Engine InnoDB
idNgTS_tm_taskmeta: Data: 2.13MB + Index: 0.06MB + Engine InnoDB
idNgTS_tm_tasks: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
idNgTS_usermeta: Data: 8.42MB + Index: 6.83MB + Engine InnoDB
idNgTS_users: Data: 0.27MB + Index: 0.23MB + Engine InnoDB
idNgTS_wcfm_affiliate_orders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_affiliate_orders_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_daily_analysis: Data: 8.02MB + Index: 7.02MB + Engine InnoDB
idNgTS_wcfm_detailed_analysis: Data: 447.98MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_enquiries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_enquiries_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_enquiries_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_enquiries_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_fbc_chat_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_fbc_chat_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_wcfm_fbc_chat_visitors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_fbc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_following_followers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_orders: Data: 2.52MB + Index: 0.38MB + Engine InnoDB
idNgTS_wcfm_marketplace_orders_meta: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_product_multivendor: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_wcfm_marketplace_refund_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_refund_request_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_reverse_withdrawal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_reverse_withdrawal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_reviews_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_reviews_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_review_rating_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_shipping_zone_methods: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_store_taxonomies: Data: 1.45MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_vendor_ledger: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_withdraw_request: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_marketplace_withdraw_request_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_membership_subscription: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_wcfm_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_messages_modifier: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_messages_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_support: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_support_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_support_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcfm_support_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcpdf_invoice_number: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
idNgTS_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wc_admin_notes: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
idNgTS_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
idNgTS_wc_category_lookup: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
idNgTS_wc_customer_lookup: Data: 0.48MB + Index: 0.38MB + Engine InnoDB
idNgTS_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
idNgTS_wc_order_coupon_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
idNgTS_wc_order_product_lookup: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
idNgTS_wc_order_stats: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
idNgTS_wc_order_tax_lookup: Data: 0.30MB + Index: 0.23MB + Engine InnoDB
idNgTS_wc_product_attributes_lookup: Data: 0.19MB + Index: 0.11MB + Engine InnoDB
idNgTS_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_wc_product_meta_lookup: Data: 0.31MB + Index: 0.56MB + Engine InnoDB
idNgTS_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_wc_zapier_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wlr_earn_campaign: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
idNgTS_wlr_earn_campaign_transaction: Data: 0.22MB + Index: 0.63MB + Engine InnoDB
idNgTS_wlr_expire_points: Data: 0.22MB + Index: 0.47MB + Engine InnoDB
idNgTS_wlr_levels: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
idNgTS_wlr_logs: Data: 0.45MB + Index: 0.14MB + Engine InnoDB
idNgTS_wlr_points_ledger: Data: 0.36MB + Index: 0.47MB + Engine InnoDB
idNgTS_wlr_referral: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_wlr_rewards: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
idNgTS_wlr_reward_transactions: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
idNgTS_wlr_users: Data: 0.14MB + Index: 0.22MB + Engine InnoDB
idNgTS_wlr_user_rewards: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
idNgTS_woo_shippment_provider: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
idNgTS_wpmailsmtp_debug_events: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
idNgTS_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wpml_mails: Data: 77.52MB + Index: 0.00MB + Engine InnoDB
idNgTS_wpr_rocket_cache: Data: 1.34MB + Index: 2.30MB + Engine InnoDB
idNgTS_wpr_rucss_used_css: Data: 2.47MB + Index: 2.48MB + Engine InnoDB
idNgTS_wps_hit: Data: 9.52MB + Index: 25.64MB + Engine InnoDB
idNgTS_wps_index: Data: 21.55MB + Index: 22.55MB + Engine InnoDB
idNgTS_wps_key: Data: 0.45MB + Index: 0.27MB + Engine InnoDB
idNgTS_wps_object_term: Data: 3.52MB + Index: 8.02MB + Engine InnoDB
idNgTS_wps_object_type: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
idNgTS_wps_query: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
idNgTS_wps_uri: Data: 0.33MB + Index: 0.22MB + Engine InnoDB
idNgTS_wps_user_agent: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
idNgTS_wsal_metadata: Data: 32.56MB + Index: 35.02MB + Engine InnoDB
idNgTS_wsal_occurrences: Data: 18.55MB + Index: 5.03MB + Engine InnoDB
idNgTS_wt_abandonment_coupon: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
idNgTS_wt_iew_action_history: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
idNgTS_wt_iew_cron: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wt_iew_ftp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_wt_iew_mapping_template: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_yith_wcan_filter_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
idNgTS_yith_wcwl: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
idNgTS_yith_wcwl_lists: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
idNgTS_yoast_indexable: Data: 13.22MB + Index: 7.72MB + Engine InnoDB
idNgTS_yoast_indexable_hierarchy: Data: 1.11MB + Index: 0.56MB + Engine InnoDB
idNgTS_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
idNgTS_yoast_primary_term: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
idNgTS_yoast_prominent_words: Data: 1.52MB + Index: 1.05MB + Engine InnoDB
idNgTS_yoast_seo_links: Data: 4.47MB + Index: 2.78MB + Engine InnoDB
idNgTS_zoo_ln_filter_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_zoo_ln_filter_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
idNgTS_zoo_ln_global_config: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
acoplw_badges: 3
acoplw_prod_list: 2
attachment: 9026
br_filters_group: 69
br_product_filter: 84
br_tabs_location: 1
cookielawinfo: 6
copy-to-clipboard: 1
custom_css: 3
e-landing-page: 1
elementor_font: 6
elementor_library: 107
filter-field: 3
filter-set: 1
jet_options_preset: 1
jet-menu: 4
jet-smart-filters: 2
jet-theme-core: 3
jet-woo-builder: 5
jp_img_sitemap: 5
jp_img_sitemap_index: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
nav_menu_item: 115
notificationx: 1
oembed_cache: 14
page: 387
payment_gateway: 1
post: 71
product: 1339
product_variation: 353
product-feed: 30
pswtm_tab: 4
revision: 4
sa_slider: 1
seedprod: 3
shop_coupon: 500
shop_order: 5017
shop_order_refund: 100
viwcpf_filter_block: 4
viwcpf_filter_menu: 1
wc_product_tab: 2
wcfm_knowledgebase: 1
wcfm_notice: 4
wp_global_styles: 2
wp_navigation: 1
wpuf_contact_form: 2
wpuf_input: 7
yith_wcan_preset: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (59) ###

Gravity Forms: by Gravity Forms – 2.7.6
Advanced Shipment Tracking Pro: by zorem – 3.0
Awin - Advertiser Tracking: by awinglobal – 1.1.4
B Social Share - Block: by bPlugins LLC – 1.0.5
Product Feed Manager for WooCommerce PRO: by RexTheme – 6.3.8
Product Feed Manager for WooCommerce: by RexTheme – 7.2.28
Botiga Pro: by aThemes – 1.2.1
Fetchify: by ClearCourse Business Services Limited t/a Fetchify – 1.6.1
Code Snippets: by Code Snippets Pro – 3.3.0
CookieYes | GDPR Cookie Consent: by CookieYes – 3.0.8
Doofinder for WooCommerce: by doofinder – 1.5.48
Yoast Duplicate Post: by Enrico Battocchi and Team Yoast – 4.5
GTM4WP: by Thomas Geiger – 1.16.2
Elementor Pro: by Elementor.com – 3.13.1
Elementor: by Elementor.com – 3.13.2
Facebook for WooCommerce: by Facebook – 3.0.23
Filter Everything PRO: by Andrii Stepasiuk – 1.7.8
Filter Everything — WooCoomerce Product & WordPress Filter: by Andrii Stepasiuk – 1.7.6
Google Listings and Ads: by WooCommerce – 2.4.2
Invoice Payment Gateway For WooCommerce: by WPExperts – 1.0
Klaviyo: by Klaviyo
Inc. – 3.0.12

Nextend Social Login: by Nextendweb – 3.1.7
Nextend Social Login Pro Addon: by Nextendweb – 3.1.7
Order Export & Order Import for WooCommerce: by WebToffee – 2.3.3
Pinterest for WooCommerce: by WooCommerce – 1.2.16 (update to version 1.2.21 is available)
Frequently Bought Together: by Premmerce – 1.0.2
PS Product Tab Manager: by Perception System Pvt. Ltd. – 1.0.0
REVIEWS.io for WooCommerce: by Reviews.co.uk – 0.4.6
Rank Math SEO PRO: by Rank Math – 3.0.33
Rank Math SEO: by Rank Math – 1.0.111
SVG Support: by Benbodhi – 2.5.5
TikTok: by TikTok – 1.0.16
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.23.3.26

View Admin As: by Jory Hogeveen – 1.8.8
WCFM - WooCommerce Frontend Manager - Analytics: by WC Lovers – 2.2.3
WCFM - WooCommerce Frontend Manager - Ultimate: by WC Lovers – 6.6.8
WCFM - WooCommerce Frontend Manager: by WC Lovers – 6.7.0
WCFM - WooCommerce Multivendor Marketplace: by WC Lovers – 3.5.10
WCFM - WooCommerce Multivendor Marketplace - REST API: by WC Lovers – 1.5.3
Preview E-mails for WooCommerce: by Digamber Pradhan – 2.1.1
Payment Plugins for Stripe WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.3.39

WooCommerce AJAX Products Filter: by BeRocket – 3.1.3.3
WooCommerce Brands: by WooCommerce – 1.6.49
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 3.4.1
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.4.0
WooCommerce Shipping & Tax: by WooCommerce – 2.2.4
WooCommerce Xero Integration: by WooCommerce – 1.7.56
WooCommerce Zapier: by OM4 Software – 2.3.1 (update to version 2.4.2 is available)
WooCommerce: by Automattic – 7.5.1 (update to version 7.7.0 is available)
WPLoyalty - WooCommerce Loyalty Points, Rewards and Referral: by Wployalty – 1.2.1
WP Mail SMTP: by WPForms – 3.7.0
Wp Maximum Upload File Size: by CodePopular – 1.0.9
WP-Optimize Premium - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.2.14

WP Rocket: by WP Media – 3.13.0.1
Order Import Export for WooCommerce Add-on: by WebToffee – 1.1.5
Product Import Export for WooCommerce Add-on: by WebToffee – 1.1.6
Import Export for WooCommerce Wrapper: by WebToffee – 1.1.9
Smart Coupons for WooCommerce  Pro: by WebToffee – 1.3.6
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.8.2

### Inactive Plugins (16) ###

Advanced Custom Fields: by WP Engine – 6.1.4
Advanced Form Integration Professional: by nasirahmed – 1.65.8
All-in-One WP Migration: by ServMask – 7.73
All-in-One WP Migration Unlimited Extension: by ServMask – 2.49
Change Admin Email Setting Without Outbound Email: by John Dee – 3.2
Classic Widgets: by WordPress Contributors – 0.3
Disable Cart Fragments: by Optimocha – 2.2
Jetpack: by Automattic – 12.0
JWT Authentication for WP-API: by Enrique Chavez – 1.3.2
Nibble Integration: by NibbleTechnology – 0.0.4
NotificationX: by WPDeveloper – 2.7.0
Simple Local Avatars: by 10up – 2.7.4
SSL Insecure Content Fixer: by WebAware – 2.7.2
WCFM - WooCommerce Multivendor Membership: by WC Lovers – 2.10.7
WooCommerce PayPal Payments: by WooCommerce – 2.0.4
WPC AJAX Search for WooCommerce (Premium): by WPClever – 2.2.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #5 - /shop/
Basket: #3134 - /cart/
Checkout: #3135 - /checkout/
My account: #149 - /my-account/
Terms and conditions: #7892 - /terms-of-use/

### Theme ###

Name: Botiga
Version: 2.0.3 (update to version 2.0.8 is available)
Author URL: https://athemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-variation-management
settings

Daily Cron: ✔ Next scheduled: 2023-05-12 20:16:27 +01:00
Options: ✔
Notes: 125
Onboarding: completed

### Action Scheduler ###

Canceled: 264
Oldest: 2023-04-12 09:30:29 +0100
Newest: 2023-05-12 14:24:13 +0100

Complete: 31,474
Oldest: 2023-04-11 16:24:46 +0100
Newest: 2023-05-12 16:24:05 +0100

Failed: 126,554
Oldest: 2021-06-22 21:34:59 +0100
Newest: 2023-05-12 16:24:05 +0100

In-progress: 1
Oldest: –
Newest: –

Pending: 56
Oldest: 2023-05-12 16:23:55 +0100
Newest: 2023-05-18 22:56:37 +0100

### WooCommerce Zapier ###

Database Version: ✔ 14
Detailed Logging Enabled: No
Legacy Mode Disabled: ✔ Yes
SSL: ✔ Yes
REST API Authentication Key(s): ❌ 0
Task History Record Count: ❌ 0

### Status report information ###

Generated at: 2023-05-12 16:24:33 +01:00
`

### PR DESCRIPTION
**Pull request by StyleT**
### Changes proposed in this Pull Request:

Other plugins often clone Woocommerce cart to do various "on the fly" calculations and now this causes duplication of the AddToCart server events.

This fixes it once and forever ;)

fixes #2544

### Screenshots:
How it looks before fix:
Screenshot 2023-09-16 at 2 19 38 PM

#### How to reproduce in tests
```
$cart = clone WC()->cart;
$cart->add_to_cart( $product_id, $qty, $variation_id, $variation )
```

#### Real-life test
Install this plugin and `woo-stripe-payment` as an example. Observe the following stack traces:

```
2023-09-16T17:51:06+00:00 DEBUG AddToCart: #0 /wp-includes/class-wp-hook.php(312): WC_Facebookcommerce_EventsTracker->inject_add_to_cart_event()
#1 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /wp-content/plugins/woocommerce/includes/class-wc-cart.php(1279): do_action()
#4 /wp-content/plugins/woo-stripe-payment/includes/controllers/class-wc-stripe-controller-cart.php(275): WC_Cart->add_to_cart()
#5 /wp-includes/rest-api/class-wp-rest-server.php(1188): WC_Stripe_Controller_Cart->cart_calculation()
#6 /wp-includes/rest-api/class-wp-rest-server.php(1035): WP_REST_Server->respond_to_request()
#7 /wp-includes/rest-api/class-wp-rest-server.php(447): WP_REST_Server->dispatch()
#8 /wp-includes/rest-api.php(418): WP_REST_Server->serve_request()
#9 /wp-content/plugins/woo-stripe-payment/includes/class-wc-stripe-rest-api.php(159): rest_api_loaded()
#10 /wp-includes/class-wp-hook.php(310): WC_Stripe_Rest_API->process_frontend_request()
#11 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#12 /wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()
#14 /wp-includes/class-wp-hook.php(310): WC_AJAX::do_wc_ajax()
#15 /wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#16 /wp-includes/plugin.php(517): WP_Hook->do_action()
#17 /wp-includes/template-loader.php(13): do_action()
#18 /wp-blog-header.php(19): require_once('/var/www/html/u...')
#19 /index.php(17): require('/var/www/html/u...')
#20 {main}
```

### Changelog entry

> Fix - AddToCart duplication when other plugins clone cart

### CODE REVIEW

**Comment by ibndawood** [comment]
Thank you, @StyleT, for your contribution. We'll have this PR reviewed by our team as soon as possible.

File: facebook-commerce-events-tracker.php [hunk 1]
```diff
@@ -563,6 +563,12 @@ public function inject_add_to_cart_event( $cart_item_key, $product_id, $quantity
 				return;
 			}
 
+			$cart = WC()->cart;
+			// Check if we're dealing with cloned cart
+			if (!isset($cart->cart_contents[ $cart_item_key ])) {
```
Comment (rawdreeg) [inline facebook-commerce-events-tracker.php:568]:
```suggestion
			if ( ! isset( $cart->cart_contents[ $cart_item_key ] ) ) {
```

**Review by rawdreeg — CHANGES_REQUESTED** [review]
Code is good, and thanks for your contribution. Just a coding style related issue to be fixed before we can merge this.

File: facebook-commerce-events-tracker.php (hunk 1 above)
Comment (rawdreeg) [reply facebook-commerce-events-tracker.php:568]: also let's add a check to make sure we can call cart_contents on $cart

**Comment by rawdreeg** [comment]
Hi @StyleT,

I have dropped a few review comments. Let us know if you have any questions.

Thanks.
R

**Review by rawdreeg — APPROVED** [review]
