### PR TITLE
Fix visibility parameter value for items if not visible.

### LINKED ISSUE #2009: Product feed visibility incorrect value
It looks like the feed is sending staging value in the visibility fieled:
image

Only `published` and hidden `values` are supported:
image

### PR DESCRIPTION
**Pull request by budzanowski**
### Changes proposed in this Pull Request:

The hidden item's visibility value was wrong. I don't really know why it was `staging`  when documentation clearly states that the values should be `hidden` or `published.

Closes #2009 .

### How to test the changes in this Pull Request:

1. Generate the feed with hidden items
2. Make sure that the feed file gets uploaded
3. Wait for feed report
4. Check for the issue mentioned in #2009

### Changelog entry

*  Fix - Feed visibilitie fild value for hidden items.

### CODE REVIEW

File: facebook-commerce.php [hunk 1]
```diff
@@ -148,7 +148,7 @@ class WC_Facebookcommerce_Integration extends WC_Integration {
 	const FB_SHOP_PRODUCT_VISIBLE = 'published';
 
 	/** @var string the API flag to set a product as not visible in the Facebook shop */
-	const FB_SHOP_PRODUCT_HIDDEN = 'staging';
+	const FB_SHOP_PRODUCT_HIDDEN = 'hidden';
```
Comment (haszari) [inline facebook-commerce.php:151]: 👌

**Review by haszari — APPROVED** [review]
Good find! I assume this is causing actual problems – i.e. `staging` items are showing up as feed errors or are visible when they should be hidden.

@budzanowski do you know what the impact of the `staging` bug is specifically? Also, do we have this bug on the old feed code, or is it only in the new engine?

**Review by rcstr — APPROVED** [review]
LGTM. updated a few references to _staging_ in comments and unit tests https://github.com/woocommerce/facebook-for-woocommerce/pull/2011/commits/080abf7224b4b1c71d86324465af336d0b4921c2

File: facebook-commerce.php (hunk 1 above)
Comment (budzanowski) [reply facebook-commerce.php:151]: Old code has the same problem.

**Comment by budzanowski** [comment]
Thanks @rcstr
