### PR TITLE
defer sending server side api events.

### LINKED ISSUE #1675: Server side sending of pixel events blocks generating pages
## 🔎 Isolate the bug
- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
Sending pixel events uses blocking PHP code which means that generating the user requested page gets paused while the event data is handled by the graph.facebook.com server. Measuring the code execution shows that the _send_api_event_ method seems to slow down the generating page between 0.5-6 seconds depending on how fast the Facebook server answers to the API requests.

##🚶‍♀️ Steps to reproduce

1. Use something like New Relic or Tideways to profile execution of pages that injects Facebook tracking (e.g. single product or product category). Alternatively use something like `curl -s -o /dev/null -w "%{time_total}\n" -H "Pragma: no-cache" https://example.com/` to measure the time for generating the selected page.
2. Measure execution of the selected pages with Facebook for Woocommerce plugin enabled
3. Measure execution of the selected pages with Facebook for Woocommerce plugin enabled or edit the facebook-commerce-events-tracker.php file to not send the API event.
4. Compare the results

## ✔️ Expected behavior
Sending pixel events should use non blocking method and/or execute sending the data to Facebook API after the page is generated and sent to user's browser.

### PR DESCRIPTION
**Pull request by rawdreeg**
### Changes proposed in this Pull Request:

Sending pixel events uses blocking PHP code, which means generating the user-requested page gets paused while the event data is handled by the graph.facebook.com server. Measuring the code execution shows that the send_api_event method seems to slow down the generating page between 0.5-6 seconds, depending on how fast the Facebook server answers to the API requests. 

This PR adds options to defer sending server-side API events until after the page has been generated.

Closes #1675.

_Replace this with a good description of your changes & reasoning._

- [ x] Do the changed files pass `phpcs` checks? Please remove `phpcs:ignore` comments in changed files and fix any issues, or delete if not practical.

### Detailed test instructions:

1. Use something like New Relic or Tideways to profile execution of pages that injects Facebook tracking (e.g. single product or product category). Alternatively use something like [Lighthouse](https://pagespeed.web.dev/).
2. Compare the results on this branch with the results on the `develop` branch

### Changelog entry

> Fix - Server side sending of pixel events blocks generating pages

### CODE REVIEW

File: facebook-commerce-events-tracker.php [hunk 1]
```diff
@@ -1258,6 +1267,32 @@ public function get_tracked_events() {
...
+
+			$pending_events = facebook_for_woocommerce()->get_integration()->events_tracker->get_pending_events();
+
+			if ( empty( $pending_events ) ) {
+				return;
+			}
+
+			foreach ( $pending_events as $event ) {
+
+				$this->send_api_event( $event);
```
Comment (message-dimke) [inline facebook-commerce-events-tracker.php:1292]: Space after `$event` is missing.
```suggestion
				$this->send_api_event( $event );
```

File: facebook-commerce-events-tracker.php [hunk 2]
```diff
@@ -1258,6 +1267,32 @@ public function get_tracked_events() {
...
+		public function get_pending_events() {
+			return $this->pending_events;
+		}
+
+		/**
+		 * Send pending events.
+		 */
+		public function send_pending_events() {
+
+			$pending_events = facebook_for_woocommerce()->get_integration()->events_tracker->get_pending_events();
```
Comment (message-dimke) [inline facebook-commerce-events-tracker.php:1284]: Why not just use `$this->get_pending_events()`, we are in the same class and object?
```suggestion
			$pending_events = $this->get_pending_events();
```

**Comment by rawdreeg** [comment]
Thanks for the change suggestions. This is ready for another round of reviews.

**Review by message-dimke — APPROVED** [review]
LGTM!
