### PR TITLE
Deletes the product from facebook once it is switched to draft.

### LINKED ISSUE #2547: Products remain on Facebook when set to draft
## ✍️ Describe the bug

Typically, when you publish a product it's synced to Facebook. When you set the same product to private or hidden, it's removed from Facebook. However, unlike when hidden and set to private, products remain on Facebook when set to draft. 

## 🚶‍♀️ Steps to reproduce

1. Sync products to Facebook as usual
2. Set the product to draft
3. Notice the product remains on Facebook while the Facebook sync widget returns "Product is not published"

## ✔️ Expected behavior

Published products should be removed from Facebook once set to draft

### PR DESCRIPTION
**Pull request by krutidugade**
### Changes proposed in this Pull Request:

Products are visible on Facebook even after switching to draft.  This PR deletes the product from Meta Commerce Manager once the product status is switched to draft. 

Closes #2547.

- [ ] Do the changed files pass `phpcs` checks? Please remove `phpcs:ignore` comments in changed files and fix any issues, or delete if not practical.

### Detailed test instructions:

1. Install and activate the Facebook for WooCommerce plugin
2. Go to Meta Commerce Manager
3. Look for a specific product and note the ID
4. Go to WP-Admin > Products and edit the same product
5. Change the product status to draft and update
6. Look for the same product under Meta Commerce Manager
7. Verify the product isn't visible - compare product ID

### CODE REVIEW

File: facebook-commerce.php [hunk 1]
```diff
@@ -927,6 +935,26 @@ public function delete_fb_product( $product ) {
...
+	 */
+	public function delete_draft_product( $new_status, $old_status, $post ) {
+
+		if ( ! $post ) {
+			return;
+		}
+
+		if ( $old_status === 'publish' && $new_status === 'draft' ) {
+			$product_id = $post->ID;
+			$this->on_product_delete ( $product_id );
```
Comment (rawdreeg) [inline facebook-commerce.php:953]:
```suggestion
			$this->on_product_delete ( $post->ID );
```

I think the variable is not needed. but that's my personal preference, you don't have to apply the change :-)

File: facebook-commerce.php [hunk 2]
```diff
@@ -368,6 +368,14 @@ public function __construct( WC_Facebookcommerce $facebook_for_woocommerce ) {
 
 		add_action( 'untrashed_post', [ $this, 'fb_restore_untrashed_variable_product' ] );
 
+		// Ensure product is deleted from FB when moved to draft.
+		add_action(
+			'transition_post_status',
+			array( $this, 'delete_draft_product' ),
+			10,
+			3
+		);
```
Comment (rawdreeg) [inline facebook-commerce.php:377]: I noticed that a few lines above, we have this action hook: https://github.com/woocommerce/facebook-for-woocommerce/blob/cccb9f88682c57166fa1b6709f19cc987fea7946/facebook-commerce.php#L367

They're doing the same thing. I'd remove that if it's not working, and I am not sure there's value in keeping both codes.

**Review by rawdreeg — APPROVED** [review]
Approved, with a couple of minor comments for your consideration.

**Comment by budzanowski** [comment]
If you look inside the `./src/wp-includes/post.php` you will find that you can use this hook:

https://github.com/WordPress/wordpress-develop/blob/bea4307daa21a3f97d159898b0ac676332e0e7de/src/wp-includes/post.php#L5363

Which uses a dynamic action name. This means that you can use a more direct action `publish_to_draft` and you are not required to do the check:

```PHP
if ( $old_status === 'publish' && $new_status === 'draft' ) 
```

File: facebook-commerce.php (hunk 2 above)
Comment (budzanowski) [reply facebook-commerce.php:377]: I don't understand this comment 😓 

One hook is for deleting, one if for trashing and one is for changing to draft :) Which one should we delete? Do I understand this correctly?

File: facebook-commerce.php (hunk 1 above)
Comment (budzanowski) [reply facebook-commerce.php:953]: I think that this would work with just `$post`.

Because the first line of `on_product_detele` is:

```PHP
	$product = wc_get_product( $product_id );
``` 

and the first param to `wc_get_product` is described as:
```PHP
 * @param mixed $the_product Post object or post ID of the product.
```

File: facebook-commerce.php (hunk 2 above)
Comment (krutidugade) [reply facebook-commerce.php:377]: We need to keep both. The new action hook only deletes the product if it is changed to draft. The existing one `add_action( 'wp_trash_post', [ $this, 'on_product_delete' ] ); ` deletes the product if it is moved to trash.

Comment (rawdreeg) [reply facebook-commerce.php:377]: Had a bit of a brain fart here. Draft and trash aren't the same. You're both correct. I will resolve the threat.

File: facebook-commerce.php (hunk 1 above)
Comment (krutidugade) [reply facebook-commerce.php:953]: @budzanowski Are you suggesting we make changes to `on_product_detele` method? If not then we'd get an error since the method accepts int parameter.

Comment (budzanowski) [reply facebook-commerce.php]: We could but lets keep it as is and just use what @rawdreeg has suggested.

**Comment by krutidugade** [comment]
@rawdreeg I found an issue with the merged code so requested a revert. I have pushed the correct code in the same branch - https://github.com/woocommerce/facebook-for-woocommerce/commit/21ae4192fde8e327510baf2021ccc2c1cd39f07a

**Comment by budzanowski** [comment]
@krutidugade In cases like this please do the revert ( if it is really just a revert change it should be OK to bypass the security review check and just merge ).

Next please create a separate PR with the correct fix.

**Comment by krutidugade** [comment]
> @krutidugade In cases like this please do the revert ( if it is really just a revert change it should be OK to bypass the security review check and just merge ).

Thanks for confirming. 

> Next please create a separate PR with the correct fix.
On it!
